/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import Logica.Manejadora;
import Logica.Principal;

/**
 *
 * @author USER
 */
public class EscogeTabla extends javax.swing.JPanel {

    int escogida=0;
    Manejadora obj = new Manejadora();
    /**
     * Creates new form EscogeTabla
     */
    public EscogeTabla() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        botTab1 = new javax.swing.JButton();
        botTab2 = new javax.swing.JButton();
        botTab3 = new javax.swing.JButton();
        botTab4 = new javax.swing.JButton();
        botTab5 = new javax.swing.JButton();
        botVover = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 255, 102));

        jLabel1.setFont(new java.awt.Font("Tekton Pro Cond", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Escoge la tabla para iniciar el juego...");

        botTab1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tabPeq/tablaAmaRoj.png"))); // NOI18N
        botTab1.setToolTipText("Fichas Blancas y Negras");
        botTab1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botTab1ActionPerformed(evt);
            }
        });

        botTab2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tabPeq/tablaBlaNeg.png"))); // NOI18N
        botTab2.setToolTipText("Fichas Rojas y Amarillas");
        botTab2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botTab2ActionPerformed(evt);
            }
        });

        botTab3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tabPeq/tablaBlaRoj.png"))); // NOI18N
        botTab3.setToolTipText("Fichas Negras y Azules");
        botTab3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botTab3ActionPerformed(evt);
            }
        });

        botTab4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tabPeq/tablaBlaAma.png"))); // NOI18N
        botTab4.setToolTipText("Fichas Verdes y Rojas");
        botTab4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botTab4ActionPerformed(evt);
            }
        });

        botTab5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tabPeq/tablaRojNeg.png"))); // NOI18N
        botTab5.setToolTipText("Fichas Blancas y Azules");
        botTab5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botTab5ActionPerformed(evt);
            }
        });

        botVover.setText("Volver");
        botVover.setToolTipText("Menu Inicial");
        botVover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botVoverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(botTab1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(botTab2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(botTab3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(botTab4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(botTab5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(67, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(166, 166, 166))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(botVover, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botTab1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botTab2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botTab3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botTab4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botTab5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botVover, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botVoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botVoverActionPerformed
        // TODO add your handling code here:
        Principal vent = new Principal();
        vent.start();
    }//GEN-LAST:event_botVoverActionPerformed

    private void botTab1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botTab1ActionPerformed
        escogida = 1;
        Principal vent = new Principal();
        obj.Cuadro1();
    }//GEN-LAST:event_botTab1ActionPerformed

    private void botTab2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botTab2ActionPerformed
        escogida = 2;
        Principal vent = new Principal();
        obj.Cuadro2();
    }//GEN-LAST:event_botTab2ActionPerformed

    private void botTab3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botTab3ActionPerformed
        escogida = 3;
        Principal vent = new Principal();
        obj.Cuadro3();
    }//GEN-LAST:event_botTab3ActionPerformed

    private void botTab4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botTab4ActionPerformed
        escogida = 4;
        Principal vent = new Principal();
        obj.Cuadro4();
    }//GEN-LAST:event_botTab4ActionPerformed

    private void botTab5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botTab5ActionPerformed
        escogida = 5;
        Principal vent = new Principal();
        obj.Cuadro5();
    }//GEN-LAST:event_botTab5ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botTab1;
    private javax.swing.JButton botTab2;
    private javax.swing.JButton botTab3;
    private javax.swing.JButton botTab4;
    private javax.swing.JButton botTab5;
    private javax.swing.JButton botVover;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
